# Generated by Django 3.1.7 on 2021-04-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=170)),
                ('email', models.CharField(max_length=170)),
                ('organisation', models.CharField(max_length=250)),
                ('query', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
