# Generated by Django 3.1.7 on 2021-04-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=170)),
                ('name_of_organization', models.CharField(max_length=170)),
                ('organization_address', models.CharField(max_length=170)),
                ('contact', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=170)),
                ('gst_no', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=16)),
                ('reenter_password', models.CharField(max_length=16)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=122)),
            ],
        ),
    ]
