# Generated by Django 3.1.7 on 2021-04-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0003_auto_20210423_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='UsrName',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='UserID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
