# Generated by Django 3.1.7 on 2021-04-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_auto_20210423_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='UserID',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='id',
            field=models.AutoField(auto_created=True, default=1001, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
