# Generated by Django 3.1.7 on 2021-04-28 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0006_auto_20210424_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_name', models.CharField(max_length=300)),
                ('material', models.CharField(choices=[('LD', 'LD'), ('BOPP', 'BOPP'), ('PP', 'PP'), ('SLD', 'SLD'), ('HM', 'HM'), ('2L', '2-Layer'), ('3L', '3-Layer'), (' FL', 'Front Laminate'), ('L', 'Laminate'), ('PF', 'Pouch/Film')], max_length=10)),
                ('dem', models.CharField(choices=[('I', 'inch'), ('MM', 'millimeters')], max_length=5)),
                ('size', models.CharField(max_length=20)),
                ('quantity', models.CharField(max_length=25)),
                ('specification', models.CharField(choices=[('PL', 'plain'), ('PR', 'print')], max_length=20)),
                ('design', models.BooleanField(default=False, max_length=10)),
                ('type_of_print', models.CharField(choices=[('F', 'flexo'), ('G', 'Gravier')], default='None', max_length=10)),
                ('tapping', models.CharField(choices=[('w/o', 'withput tape'), ('F', 'flap'), ('SB', 'side blade'), ('FT', 'flaptape')], max_length=20)),
                ('cust_name', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('Cust_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.userinfo')),
            ],
        ),
    ]
