# Generated by Django 3.1.7 on 2021-04-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0008_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dem',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='design',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_of_print',
            field=models.CharField(choices=[('F', 'flexo'), ('G', 'Gravier')], default=None, max_length=10),
        ),
    ]
