# Generated by Django 3.1.7 on 2021-04-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0009_auto_20210428_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='material',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='specification',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='tapping',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_of_print',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
