# Generated by Django 3.1.7 on 2021-04-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0010_auto_20210428_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Cust_ID',
            new_name='Cust',
        ),
        migrations.AlterField(
            model_name='order',
            name='material',
            field=models.CharField(max_length=200),
        ),
    ]
