# Generated by Django 3.1.7 on 2021-04-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0013_auto_20210428_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
