# Generated by Django 3.1.7 on 2021-04-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0014_remove_order_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
