# Generated by Django 3.1.7 on 2021-04-28 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0015_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_name', models.CharField(max_length=300)),
                ('material', models.CharField(max_length=200)),
                ('dem', models.CharField(max_length=5)),
                ('size', models.CharField(max_length=20)),
                ('quantity', models.CharField(max_length=25)),
                ('specification', models.CharField(max_length=20)),
                ('design', models.CharField(default=False, max_length=10)),
                ('type_of_print', models.CharField(default=None, max_length=10)),
                ('tapping', models.CharField(max_length=20)),
                ('cust_name', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('status', models.CharField(default='ongoing', max_length=30)),
                ('Cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.userinfo')),
            ],
        ),
    ]
