# Generated by Django 3.1.7 on 2021-04-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0016_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
