# Generated by Django 3.1.7 on 2021-04-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0017_auto_20210429_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdt',
            fields=[
                ('updtId', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(max_length=10)),
                ('updtDesc', models.CharField(max_length=5000)),
                ('date', models.DateField()),
            ],
        ),
    ]
