# Generated by Django 3.1.7 on 2021-04-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0019_auto_20210430_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
