# Generated by Django 3.1.7 on 2021-04-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0020_auto_20210430_1336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
