# Generated by Django 3.1.7 on 2021-04-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0022_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
