# Generated by Django 3.1.7 on 2021-05-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0026_auto_20210530_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='cylsize',
            field=models.IntegerField(blank=True),
        ),
    ]
